Implement basic contentable functionality
plank/contentable pull request #6
Opened 2023-08-31 20:49 UTC by m-triassi

# Description
Closes #1 

Adds traits and interfaces that allow any model to be renderable or contentable. Adds base content pivot model. Adds helper functions to render set of modules to JSON or HTML in single function call.

2023-11-01 10:18 UTC, kfriars requested changes
Quite a bit of feedback here. I spent a good amount of time thinking this one through, and look forward to the further discussion of my comments.

2023-11-01 10:18 UTC, kfriars commented on src/Concerns/CanRender.php
> +        });
If you redefine the `renderable` relation to `content` (see comment below),  and also move the cache clearing logic to the Content Model/Interface (See other suggestion) this should become:

```suggestion
        static::updated(function (Renderable $renderable) {
            $renderable->contentable()?->clearContentCache();
        });
```

2023-11-01 10:18 UTC, kfriars commented on src/Concerns/CanRender.php
> +        });
```suggestion
        static::deleted(function (Renderable $renderable) {
            $renderable->contentable()?->clearContentCache();
        });
```

2023-11-01 10:18 UTC, kfriars commented on src/Concerns/CanRender.php
> +        if (method_exists(new self(), 'bootSoftDeletes')) {
The Framework and other packages tend to use:

```php
in_array(SoftDeletes::class, class_uses_recursive(static::class))
```

2023-11-01 10:18 UTC, kfriars commented on src/Concerns/CanRender.php
> +            });
```suggestion
            static::restored(function (Renderable $renderable) {
                $renderable->contentable()?->clearContentCache();
            });
```

2023-11-01 10:18 UTC, kfriars commented on src/Contentable.php
> +        }
I would move this to `HasContent` and add it to the `Contentable` interface as `public function clearCache(): void`. The "content cache" in the implementation is directly tied to the individual `Contentable` things.

2023-11-01 10:18 UTC, kfriars commented on src/Contracts/Contentable.php
> +    public function scopeInRenderableOrder(Builder $q): void;
Should be moved to the `Content` model imo.

2023-11-01 10:18 UTC, kfriars commented on src/Contracts/Contentable.php
> +    public function attachContent(Renderable $renderable);
From discussion above, I think this should be out of scope for this package.

2023-11-01 20:22 UTC, m-triassi commented on src/Contentable.php
> +        }
Yeah that's an excellent point. We don't really need this overarching class at all. Refactoring!

2023-11-01 20:24 UTC, m-triassi commented on src/Concerns/HasContent.php
> +    }
I think this might be a bygone artifact from a previous architecture, but i kept the ability to order things. I agree though, it makes sense for the order to come from the content model instead. I'll move that over

2023-11-01 20:28 UTC, m-triassi commented on src/Concerns/CanRender.php
> +    }
This generally makes sense to me, but since the `content()` relation is a `MorphMany` it returns a collection. So i'm going to type the `contentable()` helper to optionally return a `Collection` instead. 

That also changes the logic you have above for the cache busting. Since we're working with collections, though i can just reach for a higher-order `->each->clearCache()`

2023-11-01 20:51 UTC, m-triassi commented on src/Concerns/CanRender.php
> +        if (method_exists(new self(), 'bootSoftDeletes')) {
Fair enough, i definitely view that as less readable but i'm ok with sacrificing readability to be more inline with community standards

2023-11-01 20:52 UTC, m-triassi commented on src/Concerns/CanRender.php
> +        });
As mentioned below, since we're getting back a `Collection` instead of a single instance, we need a call to `->each` (or a foreach lookp) here, but otherwise i agree with the suggestions!

2023-11-01 20:53 UTC, m-triassi commented on src/Contracts/Contentable.php
> +    public function scopeInRenderableOrder(Builder $q): void;
Agree'd!

2023-11-01 21:11 UTC, m-triassi commented on src/Concerns/HasContent.php
> +    }
This piece of feedback is the only i'm kind of agonizing over the most. I'm not sure that if i'm fully convinced it is out of scope since we have a `MorphMany` relationship on `contents()` (for any `Contentable` model) the `sync()`method doesn't actually exist which makes it quite annoying to add new content. In the context of Nova, i'm almost certain this would cut down on the code needed in the resolvers.

If you feel really strongly though, we can drop these methods, and let the package consumer handle it

2023-11-01 21:12 UTC, m-triassi commented on src/Contracts/Contentable.php
> +    public function attachContent(Renderable $renderable);
i'll leave this unresolved, but we can have our discussion on this issue in the unresolved comment above

2023-11-02 08:22 UTC, kfriars commented on src/Concerns/HasContent.php
> +    }
I dont feel strongly about it. Let's leave it in, and if it feels like it wasn't adding much value, overcomplicating things or not providing the functionality we need, we can always take it out later and release a new major version.

If you want to keep it in, it should probably go to that one extra level where it can handle arbitrary data on the content model. Shouldn't be much from where you are. The `formatKeys` method should be more similar to `InteractsWithPivotTable@formatRecordsList`, to allow you to attach arbitrary data while creating the intermediate `Content` models.

ie: when you provide an array, you assume the user knew what they were doing and used yout `[$id => [...$attributes]]` format.

2023-11-02 08:38 UTC, kfriars commented on src/Concerns/CanRender.php
> +    }
This one I do have strong opinions about, but this package is your lead, so if you still feel strongly like $renderable -> $content should be a `hasMany` it is your call.

I think in our tradition Page/Modules approach we had it right. One Module is associated with one page. I don't see a case for a Renderable belonging to more than one Contentable. ie: a text module belonging to multiple pages. Further, inside of nova that wouldn even be possible without providing extra functionality for them to link their renderable onto some other contentable.


Used chatgpt for the following. Awesome:
```mermaid
classDiagram
    class Contentable {
    }
    class Content {
    }
    class Renderable {
    }
    Contentable "1" -- "0..*" Content : contents
    Content "1" -- "1" Renderable : renderable
```

2023-11-02 09:19 UTC, kfriars commented on src/Concerns/HasContent.php
> +    private function formatKeys(Renderable|Collection|array $renderables)
One small thing which can be ignored if you choose. But the typingting technically needs to change or the interface needs to add `getKey()`. I would opt for changing the typehint.

You also would need to import the Model class if you opt to make this change. I will add a suggestion above which you can choose to commit or ignore along with this.

```suggestion
    private function formatKeys((Model&Renderable)|Collection|array $renderables)
```

2023-11-02 09:19 UTC, kfriars commented on src/Concerns/HasContent.php
> +use Illuminate\Database\Eloquent\Collection as EloquentCollection;
Paired with other comment.

```suggestion
use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Database\Eloquent\Model;
```

2023-11-02 13:39 UTC, m-triassi commented on src/Concerns/CanRender.php
> +    }
Ah i see, i assumed you wanted to keep it `MorphMany` based off your code suggestion. I think theres some good logic behind making it `MorphOne` i can look into doing that

2023-11-02 19:05 UTC, m-triassi commented on src/Concerns/CanRender.php
> +    }
I made this change and it seems to work just fine with all the existing code! Lets stick with it :)

2023-11-02 19:19 UTC, m-triassi commented on src/Concerns/HasContent.php
> +    }
I like that plan, let's check back in later with these functions and evaluate if they end up being useful. 

Im not sure i follow what you mean in the second paragraph though -- currently the sync / attach / detach function allow you to pass in any renderable content (array or otherwise), and attaches them while creating any needed intermediary content entries. This should be working exactly the same way `sync()` works on the vanilla many-to-* relations; pass data, get pivots created, report changes.

Maybe i'm misinterpreting what you mean? lmk!

2023-11-02 19:19 UTC, m-triassi commented
Ok (i think) we're almost ready for prime time? re-requesting review 🤞

2023-11-03 07:39 UTC, kfriars commented on src/Concerns/HasContent.php
> +    }
I don't see it in the implementation. I will test it out and report back. Maybe my 🧠 is just 💤 ...

2023-11-03 11:45 UTC, kfriars commented on src/Concerns/HasContent.php
> +    }
Woops. Meant to reply here earlier. The following is why I said this feels "out of scope".

As far as I can see and have tested, this implementation does not support atttaching arbitrary data to the Content pivot. To do it well "in my opinioin", would involve adding substantial amounts of logic and creating and enforcing a new structure to the `sync`, `attach`, etc. methods than Laravel users are used to and expect.

Here is a sample test I created, that still has a glaring issue but highlights the functionality I am referencing:

```php
it('allows you to add custom data to each pivot when attaching many renderables using attachContent', function () {
    expect(Content::query()->count())->toEqual(0);

    $page = Page::factory()->create();
    [$a, $b, $c] = FakeModule::factory()->count(3)->create()->toArray();

    $page->attachContent([
        $a->id => [
            'identifier' => 'First',
            'order' => 1,
            'narration' => 'I want this one to go first!'
        ],
        $b->id => [
            'identifier' => 'Second',
            'order' => 2,
            'narration' => 'I want this one to go second!'
        ],
        $c->id => [
            'identifier' => 'Third',
            'order' => 3,
            'narration' => 'I want this one to go third!'
        ]
    ]);

    [$one, $two, $three] = Content::query()->orderByDesc('order')->get()->toArray();
    
    expect($one->contentable_id)->toEqual($page->id);
    expect($one->contentable_type)->toEqual($page::class);
    expect($one->renderable_id)->toEqual($a->id);
    expect($one->renderable_type)->toEqual($a::class);
    expect($one->order)->toEqual(1);
    expect($one->narration)->toEqual('I want this one to go first!');

    expect($two->contentable_id)->toEqual($page->id);
    expect($two->contentable_type)->toEqual($page::class);
    expect($two->renderable_id)->toEqual($b->id);
    expect($two->renderable_type)->toEqual($b::class);
    expect($two->order)->toEqual(2);
    expect($two->narration)->toEqual('I want this one to go second!');

    expect($three->contentable_id)->toEqual($page->id);
    expect($three->contentable_type)->toEqual($page::class);
    expect($three->renderable_id)->toEqual($c->id);
    expect($three->renderable_type)->toEqual($c::class);
    expect($three->order)->toEqual(3);
    expect($three->narration)->toEqual('I want this one to go third!');
});
```

Here we are attaching arbitrary pivot data to the Content model, and I think it is reasonable to expect package consumers will have their own needs on their Content models.

The above format is what Laravel users are used to for syncing/attaching many records to pivots. The glaring issue is that this is not sufficient for our polymorph to polymorph pivot table. The reason being, the `$id` defined in these arrays is not truly identifying, since it is missing its accompanying `renderable_type`.

You would need to create a data structure and convention, and rewrite mostly allof the logic of `InteractsWithPivotTable` to provide the `attach`, `sync` etc. methods you are trying to recreate here.

This is illegal syntax, but demonstrates the new type of data structure I think would make this possible:
```php
    $page->attachContent([
        [$a->id, $a::class] => [ ...$attributes],
    ]);
```
You could add a convention like `[$renderable, [...$attributes]]` but you would still need to rewrite all of the logic I referenced earlier to accommodate this.

Your current `syncContent` method provides no opportunity for any pivot data to be created/update.
Your `attachContent` method only supports an `identifier` when passed a single `Renderable`, or attaching multiple `Renderable`s with the same identifier.

******

So in summary, my original opinion that this is out of scope for the package holds. If choosing between working directly with the `Content` model in a way you are already familiar with as a Laravel user, versus writing a good chunk of code + forcing package consumers to learn your new convention – for now at least – I would lean towards the former.

2023-11-03 16:13 UTC, m-triassi commented on src/Concerns/HasContent.php
> +    }
Hmm i see what you mean now, yeah you're right there isn't a clean way to pass pivot data in the function 🤔 That's really unfortunate i would have really preferred to keep this in the package. Oh well, i'll rip it out then!

2023-11-03 18:15 UTC, kfriars commented on src/Concerns/HasContent.php
> +    }
If you were to implement this functionality, I honestly think it could warrant its own package.

A 'morphAny' pseudo relationship of sorts.

2023-11-08 10:55 UTC, kfriars approved these changes
Looks good. A couple thoughts, but can totally 🚢 as is.

2023-11-08 10:55 UTC, kfriars commented on src/Contracts/Content.php
> +    public function renderOrderColumnField(): string;
I think it is good to provide this in the default Model we ship, since I assume it is a 90%+ usecase, but I think people should be able to ship Content models without ordering.

You don't consume these methods from the interface anywhere else in the package, so should be safe to remove. If you rely on this elsewhere in the package in the future, we can add them into the contract then.

```suggestion
```

2023-11-08 15:23 UTC, m-triassi commented on src/Contracts/Content.php
> +    public function renderOrderColumnField(): string;
fair enough!

2023-11-08 15:32 UTC, merged